package be.dabla.model.app;

import be.dabla.model.app.common.PersonAM;
import oracle.adf.share.logging.ADFLogger;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 03 10:08:43 CEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonAMImpl extends ApplicationModuleImpl implements PersonAM {

    private static ADFLogger logger =
        ADFLogger.createADFLogger(PersonAMImpl.class);
    
    /**
     * This is the default constructor (do not remove).
     */
    public PersonAMImpl() {
    }

    /**
     * Container's getter for PersonVO.
     * @return PersonVO
     */
    public ViewObjectImpl getAddressTypeVO() {
        return (ViewObjectImpl)findViewObject("PersonVO");
    }
}
