package be.dabla.model.app.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 11 15:44:21 CEST 2011
// ---------------------------------------------------------------------
public interface PersonAM extends ApplicationModule {

}