package be.dabla.model.view;

import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 04 10:27:35 CET 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonVOImpl extends ViewObjectImpl {

    /**
     * This is the default constructor (do not remove).
     */
    public PersonVOImpl() {
    }
}