package be.dabla.model.app.client;

import be.dabla.model.app.common.PersonAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 03 11:02:09 CEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonAMClient extends ApplicationModuleImpl implements PersonAM {
    /**
     * This is the default constructor (do not remove).
     */
    public PersonAMClient() {
    }
}